In [4]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Step1: define model strcutrue

In [5]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([layers.Dense(512, activation="relu"),
                          layers.Dense(10, activation="softmax")])

# Desne : fully connected layers: (ANN)  all input neurons are connected to next layer all neurons

# Step2: compile model : define loss function, optimizer, performance metrics

In [6]:
model.compile(optimizer="rmsprop",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

# rmsprop
# loss : since we have multiclass classifcaation: [0,1,2,3,4,5,6,7,8,9]
#         sparse categorical cross entropy
# for binary : binary cross entropy
# metric: performance metrics : accuracy , precsion , recall, f1_score 

In [7]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [8]:
import numpy as np
images = np.arange(27).reshape(3,3,3)
images

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
images.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [10]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.8751 - loss: 0.4328
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9666 - loss: 0.1145
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9788 - loss: 0.0708
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - accuracy: 0.9850 - loss: 0.0499
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - accuracy: 0.9905 - loss: 0.0351


In [11]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step


In [12]:
for pred in predictions:
    print(pred.argmax())   

7
2
1
0
4
1
4
9
6
9


In [13]:
test_labels[0:10]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9], dtype=uint8)

In [14]:
model.save("handwritten_digit_classifier.keras")
# loaded_model = keras.saving.load_model("handwritten_digit_classifier.keras")

In [2]:
from PIL import Image
import numpy as np

def prediction(image_path):    
  image = Image.open(image_path).convert("L")  # Convert to grayscale
  image = image.resize((28, 28))  # Resize to match MNIST format
  image_array = np.array(image).astype('float32') / 255  # Normalize
  image_array = image_array.reshape((1, 784))  # Reshape for model input
  prediction = model.predict(image_array)
  predicted_label = np.argmax(prediction)
  print(f"Predicted digit: {predicted_label}")

In [3]:
prediction("G:\Saylani2025\Saylani2024\Batch8\DataAnalysis\ML\DeepLearning\six.png")

<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
C:\Users\Nasir Hussain\AppData\Local\Temp\ipykernel_14808\1552428986.py:1: SyntaxWarning: invalid escape sequence '\S'
  prediction("G:\Saylani2025\Saylani2024\Batch8\DataAnalysis\ML\DeepLearning\six.png")
C:\Users\Nasir Hussain\AppData\Local\Temp\ipykernel_14808\1552428986.py:1: SyntaxWarning: invalid escape sequence '\S'
  prediction("G:\Saylani2025\Saylani2024\Batch8\DataAnalysis\ML\DeepLearning\six.png")


NameError: name 'model' is not defined

In [16]:
train_images[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
rf = RandomForestClassifier()

In [19]:
rf.fit(train_images,train_labels)

RandomForestClassifier()

In [20]:
y_pred = rf.predict(test_images)

In [22]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(test_labels, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.96      0.97      0.97      1032
           3       0.96      0.97      0.96      1010
           4       0.97      0.97      0.97       982
           5       0.97      0.97      0.97       892
           6       0.97      0.98      0.97       958
           7       0.97      0.96      0.97      1028
           8       0.96      0.96      0.96       974
           9       0.96      0.95      0.95      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000



In [23]:
confusion_matrix(test_labels,y_pred)

array([[ 969,    0,    1,    0,    0,    2,    4,    1,    3,    0],
       [   0, 1124,    3,    2,    0,    2,    3,    0,    0,    1],
       [   6,    0, 1001,    4,    2,    0,    3,    9,    7,    0],
       [   0,    0,    9,  975,    1,    7,    0,    9,    8,    1],
       [   1,    0,    1,    0,  957,    0,    5,    0,    3,   15],
       [   2,    0,    0,   14,    2,  861,    4,    2,    6,    1],
       [   7,    3,    1,    0,    4,    5,  935,    0,    3,    0],
       [   1,    3,   19,    1,    1,    0,    0,  990,    2,   11],
       [   3,    0,    4,    9,    4,    4,    6,    3,  931,   10],
       [   5,    6,    1,    9,   14,    7,    1,    3,    6,  957]],
      dtype=int64)