In [1]:
import numpy as np

In [3]:
a = np.zeros((4,4))
b = np.ones((4,4))

In [5]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.hstack((a,b))

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [11]:
np.vstack((a,b))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
c = np.zeros((3,3))

In [15]:
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.hstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 3

In [21]:
a = np.arange(16).reshape(4,4)
b = np.arange(16,32).reshape(4,4)

In [23]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
b

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [29]:
np.dstack((a,b))

#numpy.dstack
'''Stacks arrays along the third axis (axis 2).
For 1D arrays, it stacks them to create a 2D array with depth.
For 2D arrays, it stacks them to create a 3D array.'''

array([[[ 0, 16],
        [ 1, 17],
        [ 2, 18],
        [ 3, 19]],

       [[ 4, 20],
        [ 5, 21],
        [ 6, 22],
        [ 7, 23]],

       [[ 8, 24],
        [ 9, 25],
        [10, 26],
        [11, 27]],

       [[12, 28],
        [13, 29],
        [14, 30],
        [15, 31]]])

In [35]:

c = np.array([1, 2, 3])
d = np.array([4, 5, 6])

result = np.dstack((c, d))
print(result)
# Output:
# [[[1 4]
#   [2 5]
#   [3 6]]]


[[[1 4]
  [2 5]
  [3 6]]]


In [39]:
e = np.array([[[1, 2],
               [3, 4]]])

f = np.array([[[5, 6],
               [7, 8]]])

result = np.dstack((e, f))
print(result)
# Output:
# [[[ 1  2  5  6]
#   [ 3  4  7  8]]]


[[[1 2 5 6]
  [3 4 7 8]]]


Let me clarify `numpy.dstack` with a simple, step-by-step explanation and visualization.

---

### **What is `numpy.dstack`?**
- `dstack` stacks arrays **along the third axis (depth axis)**.
- Think of it as "depth stacking" where elements of input arrays are layered like pages in a book.

---

### **Key Points**
1. **For 1D arrays**: It creates a 2D array with depth 2.
2. **For 2D arrays**: It creates a 3D array by adding a new depth dimension.
3. **For 3D arrays**: It stacks along the third axis.

---

### **Examples**

#### **1. Stacking 1D Arrays**
```python
import numpy as np

a = np.array([1, 2, 3])  # Shape: (3,)
b = np.array([4, 5, 6])  # Shape: (3,)

result = np.dstack((a, b))
print(result)
```

**Output**:
```plaintext
[[[1 4]
  [2 5]
  [3 6]]]
```

**Explanation**:
- `a` and `b` are 1D arrays with 3 elements each.
- After stacking:
  - A new dimension (depth) is added.
  - Each element of `a` and `b` is paired along the depth axis:
    ```
    [
        [ [1, 4], [2, 5], [3, 6] ]
    ]
    ```
- The result is a **3D array** with shape `(1, 3, 2)`:
  - `1`: 1 "row" (new axis added by `dstack`).
  - `3`: 3 elements in each row.
  - `2`: Depth created by combining `a` and `b`.

---

#### **2. Stacking 2D Arrays**
```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])  # Shape: (2, 3)

b = np.array([[7, 8, 9],
              [10, 11, 12]])  # Shape: (2, 3)

result = np.dstack((a, b))
print(result)
```

**Output**:
```plaintext
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
```

**Explanation**:
- `a` and `b` are 2D arrays with the same shape `(2, 3)`.
- After stacking:
  - Each element in `a` is paired with the corresponding element in `b` along the depth axis.
    ```
    [
        [ [1, 7], [2, 8], [3, 9] ],
        [ [4, 10], [5, 11], [6, 12] ]
    ]
    ```
- The result is a **3D array** with shape `(2, 3, 2)`:
  - `2`: Number of rows.
  - `3`: Number of columns.
  - `2`: Depth (number of arrays stacked).

---

#### **3. Stacking 3D Arrays**
```python
a = np.array([[[1, 2],
               [3, 4]]])  # Shape: (1, 2, 2)

b = np.array([[[5, 6],
               [7, 8]]])  # Shape: (1, 2, 2)

result = np.dstack((a, b))
print(result)
```

**Output**:
```plaintext
[[[ 1  2  5  6]
  [ 3  4  7  8]]]
```

**Explanation**:
- `a` and `b` are 3D arrays with the same shape `(1, 2, 2)`.
- After stacking:
  - Their depth dimensions are combined, resulting in a deeper array:
    ```
    [
        [
            [1, 2, 5, 6],
            [3, 4, 7, 8]
        ]
    ]
    ```
- The result is a **3D array** with shape `(1, 2, 4)`:
  - `1`: Number of pages (unchanged).
  - `2`: Number of rows.
  - `4`: Depth (2 original + 2 stacked).

---

### **Visualizing Dimensions**

#### Before `dstack`:
- `a`:  
  ```
  [[1, 2, 3],
   [4, 5, 6]]
  ```

- `b`:  
  ```
  [[7, 8, 9],
   [10, 11, 12]]
  ```

#### After `dstack`:
Depth layer 1 (from `a`):
```
[[1, 2, 3],
 [4, 5, 6]]
```

Depth layer 2 (from `b`):
```
[[7, 8, 9],
 [10, 11, 12]]
```

Combined:
```
[[[ 1, 7],
  [ 2, 8],
  [ 3, 9]],
 [[ 4, 10],
  [ 5, 11],
  [ 6, 12]]]
```

---

### **Key Takeaway**
- `dstack` adds depth to the arrays.
- Use it when you need to work with an additional "layer" of data (e.g., for image processing or pairing corresponding elements).

Let me know if you need further clarification or use cases!

In [42]:
np.concatenate((a, b), axis = 1)

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [44]:
np.concatenate((a, b), axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [46]:
np.column_stack((a,b))

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [48]:
np.row_stack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

### hstack == column_stack == axis=1
### vstack == row_stack    == axis=0

# Splitting Arrays

In [52]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [56]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [58]:
np.hsplit(a,3)

ValueError: array split does not result in an equal division

In [60]:
np.hsplit(a,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [62]:
np.split(a, 2, axis = 1)  # basically column split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [64]:
np.split(a, 2, axis = 0)   # basically row split 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

### Understanding Axes in NumPy
- Axis 0: Refers to rows (the "vertical" direction).
Operations along axis 0 act across rows.
- Axis 1: Refers to columns (the "horizontal" direction).
Operations along axis 1 act across columns.

# Numerical Methods of Numpy Arrays


In [69]:
m = np.array([[34,56,23],[2,76,8],[8,7,0]])
print (m)

[[34 56 23]
 [ 2 76  8]
 [ 8  7  0]]
